version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/
      - backend_node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - JWT_SECRET=SECRET
      - PORT=3000
    depends_on:
      - postgres
  postgres:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  backend_node_modules:
